name: windows-x64

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version information (e.g., 1.8.2)"
        required: true

permissions:
  contents: write

env:
  WHISPER_VERSION: ${{ github.event.release.tag_name || github.event.inputs.version || '1.8.2' }}

jobs:
  windows_x64:
    name: Build whisper.cpp lib for Windows x64 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache build result for ${{ env.WHISPER_VERSION }}
        id: cache-build-result
        uses: actions/cache@v4
        with:
          path: whisper-cpp-win-x64-static_lib-${{ env.WHISPER_VERSION }}
          key: whisper-cpp-win-x64-${{ env.WHISPER_VERSION }}-cache-v1

      - name: ccache
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-x64

      - name: Update whisper.cpp submodule
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo ${{ env.WHISPER_VERSION }} > WHISPER_VERSION
          git submodule update --init --recursive --depth=1 whisper.cpp
          cd whisper.cpp
          git fetch origin tag v${{ env.WHISPER_VERSION }}
          git checkout v${{ env.WHISPER_VERSION }}

      - name: Setup CUDA Toolkit
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: Jimver/cuda-toolkit@v0.2.16
        with:
          cuda: '12.9.1'
          method: 'network'
          sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'

      - name: Setup vcpkg
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV

      - name: Install dependencies
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python3 -m pip install cmake ninja
          cmake --version
          ninja --version

      - name: Build whisper.cpp for Windows x64 Release
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version
          
          # Configure
          cmake -S . --preset=release
          
          # Build
          cmake --build --preset=release

      - name: Collect result
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ls -lh build/release/whisper.cpp_static/
          ls -lh build/release/whisper.cpp_static/include
          ls -lh build/release/whisper.cpp_static/lib

          dst=whisper-cpp-win-x64-static_lib-${{ env.WHISPER_VERSION }}
          mkdir $dst
          cp -r build/release/whisper.cpp_static/* $dst/

      - name: zip results
        shell: bash
        run: |
          dst=whisper-cpp-win-x64-static_lib-${{ env.WHISPER_VERSION }}
          7z a -tzip $dst.zip $dst
          ls -lh

      - name: Upload v${{ env.WHISPER_VERSION }}
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: "./*.zip"
          overwrite: true
          repo_name: ${{ github.repository }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.WHISPER_VERSION }}

      - uses: actions/upload-artifact@v5
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        with:
          name: whisper-cpp-win-x64-static_lib
          path: whisper-cpp-win-x64-static_lib*.zip
